
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.showSql=true
hibernate.connection.driverClass=com.mysql.cj.jdbc.Driver
hibernate.connection.url=${DB_URL:jdbc:mysql://localhost:3306/alumni_network}
hibernate.connection.username=${DB_USERNAME:root}
hibernate.connection.password=${DB_PASSWORD:Nhat#1908}

# Cloudinary Configuration
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dlnru7sj1}
cloudinary.api_key=${CLOUDINARY_API_KEY:443123929874918}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:vuLdl_T1Ho7zi4fHZePrHUbF8gw}
